test:
  sessions:
    default:
      database: mongoid_test
      hosts:
        - 127.0.0.1:27017
      options:
        read: primary
        # In the test environment we lower the retries and retry interval to
        # low amounts for fast failures.
        max_retries: 1
        retry_interval: 0